spring:
  application:
    name: ai-code-helper
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

server:
  port: 8081
  servlet:
    context-path: /api
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: sk-6e51bdaf2e8f46d5a5d7bc6119181ddd
      streaming-chat-model:
        model-name: qwen-max
        api-key: sk-6e51bdaf2e8f46d5a5d7bc6119181ddd
      embedding-model:
        model-name: text-embedding-v4
        api-key: sk-6e51bdaf2e8f46d5a5d7bc6119181ddd
bigmodel:
  api-key: sk-6e51bdaf2e8f46d5a5d7bc6119181ddd


minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin  # 替换为实际的AccessKey
  secretKey: minioadmin  # 替换为实际的SecretKey
  bucketName: ai-intell-iq  # 自定义存储桶名称

# RAG 相关配置
rag:
  # 文档加载配置
  document:
    # 文档存放路径（支持绝对路径或相对路径）
    path: src/main/resources/docs

  # 文档分割器配置
  splitter:
    # 分割策略：paragraph（按段落）、sentence（按句子）
    type: paragraph
    # 最大片段长度
    max-length: 1000
    # 片段重叠长度（提升上下文连贯性）
    overlap: 200

  # 检索器配置
  retriever:
    # 最大返回结果数
    max-results: 5
    # 最低匹配分数（过滤不相关结果）
    min-score: 0.75

  # 文档嵌入配置
  ingest:
    # 是否异步加载文档（大量文档时建议开启，避免阻塞应用启动）
    async: true